// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:647005562784:android:d3bde0d05ac2992bbaa6c5',
    messagingSenderId: '647005562784',
    projectId: 'edubrary-d4ce1',
    storageBucket: 'edubrary-d4ce1.appspot.com',
    apiKey: 'AIzaSyDoXd4seIqx66nxnPAjLJROMmBXcjI3gqo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:647005562784:ios:fb1c22138985d534baa6c5',
    messagingSenderId: '647005562784',
    projectId: 'edubrary-d4ce1',
    storageBucket: 'edubrary-d4ce1.appspot.com',
    androidClientId: '647005562784-87la0tbrtrl31fhi40cgakh21vqoffh6.apps.googleusercontent.com',
    iosBundleId: 'com.chaudharydev.greetingshub',
    apiKey: 'AIzaSyAhVu79EXw0NceHrQsnwbTpX7UGxwsyQm4',
  );

}
